CREATE (:Epoch {id:1, name: 'Палеолит'})
CREATE (:Epoch {id:2, name: 'Мезолит'})
CREATE (:Epoch {id:3, name: 'Неолит'})
CREATE (:Epoch {id:4, name: 'Энеолит'})
CREATE (:Epoch {id:5, name: 'Бронзовый век'})
CREATE (:Epoch {id:6, name: 'Ранний железный век'})
CREATE (:Epoch {id:7, name: 'Великое переселение народов'})
CREATE (:Epoch {id:8, name: 'Средневековье'})
CREATE (:Epoch {id:9, name: 'Новое время'})